### ISSUE TITLE
Should you have an __init__.py file under the tests directory?

### ISSUE THREAD

**Issue by gordonwatts** [iris-hep/ast-language#5]
That usually tells python that tests is a package that should be installed in the system - which is definitely not what you want to do (the auto package scanners all work that way).

**Comment by masonproffitt** [comment]
Yes, this is standard practice so that tests can figure out where the actual package is. Nearly every Python package I've seen does this (e.g., [numpy](https://github.com/numpy/numpy/tree/master/numpy/tests)). If you run a Python script that sits in a directory with a `__init__.py` in it, the import system will automatically look for packages in the parent directory. Removing that file would cause the tests to fail and would then require modifying the `path` variable in every test file.
